name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que você estiver usando

jobs:
  build:
    runs-on: ubuntu-latest
    # Adicione as permissões necessárias para usar o actions/upload-pages-artifact
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Se o seu index.html estiver na raiz do repositório, use '.'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Permissões para publicar no Pages
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
